spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

  output:
    ansi:
      enabled: always
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    hexlet.code.app: DEBUG

debug: true